<a href="https://colab.research.google.com/github/jscienciadados/ciencia-dados/blob/main/Intro_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<font color="Chocolate">Processamento de Linguagem Natural</font>

In [1]:
# Imports
import numpy
import torch
import torchvision

#Criando e Manipulando Tensores
A razão pela qual usamos o Numpy em Machine Learning é que é muito mais rápido do que as listas Python na execução de operações de matriz.

Por quê? Internamente, NumPy faz a maior parte do trabalho pesado em Linguagem C, que é muito mais veloz que Python.

Mas, no caso de treinar redes neurais profundas (Deep Learning), os arrays NumPy levariam meses para treinar algumas das redes de ponta. É aqui que os tensores entram em cena. O PyTorch nos fornece uma estrutura de dados chamada Tensor, que é muito semelhante à matriz ND do NumPy. Mas, diferentemente do último, os tensores podem aproveitar os recursos de uma GPU para acelerar significativamente as operações com matrizes

In [2]:
# Criando um tensor
x = torch.tensor([1., 2.])
print(x)

tensor([1., 2.])


In [3]:
# shape
print(x.shape)

torch.Size([2])


In [4]:
# Criando um tensor
t = torch.tensor([[1,1,1,1],
                  [2,2,2,2],
                  [3,3,3,3]], dtype = torch.float32)


In [5]:
# size
t.size()

torch.Size([3, 4])

In [6]:
# shape
t.shape

torch.Size([3, 4])

No PyTorch, o tamanho e a forma de um tensor significam a mesma coisa.

Normalmente, depois de conhecermos a forma de um tensor, podemos deduzir algumas coisas. Primeiro, podemos deduzir o rank do tensor. O rank de um tensor é igual ao comprimento da forma do tensor.

In [7]:
len(t.shape)

2

In [8]:
len(x.shape)

1

Também podemos deduzir o número de elementos contidos no tensor. O número de elementos dentro de um tensor (12 no nosso caso do tensor t e 2 no tensor x) é igual ao produto dos valores dos componentes da forma.


In [9]:
torch.tensor(t.shape).prod()

tensor(12)

In [10]:
torch.tensor(x.shape).prod()

tensor(2)

In [11]:
# retornando um elemento de um tensor
z = torch.tensor([[1., 2.], [5., 3.], [0., 4.]])
print(z)

tensor([[1., 2.],
        [5., 3.],
        [0., 4.]])


In [12]:
# shape
print(z.shape)

torch.Size([3, 2])


In [13]:
# retornando a primeira do tensor e a segunda coluna
# => o retorno e no formato de tensor
print(z[0][1])

tensor(2.)


In [16]:
# retornando a primeira linha e segunda coluna
# => o retorno e no formato de escalar (apenas o valor)
print(z[0][1].item())

2.0


Quando criamos tensores com valores randomicos, passamos apenas o numero de dimensoes.

In [17]:
input1 = torch.randn([1, 4, 4, 2])
input2 = torch.rand(1, 4, 4, 2)

In [18]:
print(input1.shape)
print(input2.shape)

torch.Size([1, 4, 4, 2])
torch.Size([1, 4, 4, 2])


In [19]:
len(input1.shape)

4

In [20]:
len(input2.shape)

4

In [21]:
input1

tensor([[[[-0.2812,  0.0985],
          [ 0.8430, -0.5725],
          [-0.6726, -0.4084],
          [ 0.5604, -0.5086]],

         [[ 0.0350, -0.5008],
          [ 1.0064, -0.9489],
          [-0.8252, -0.6984],
          [-0.9657, -1.0319]],

         [[-0.3088, -0.6868],
          [-1.0448, -0.0854],
          [-0.0951, -0.0201],
          [ 0.4731,  0.4778]],

         [[-0.2382, -0.3483],
          [-0.5762, -0.5422],
          [-0.2174, -0.4519],
          [ 0.7859,  0.1755]]]])

In [22]:
input2

tensor([[[[0.8505, 0.4611],
          [0.3485, 0.5756],
          [0.8690, 0.1048],
          [0.0654, 0.4697]],

         [[0.0436, 0.9282],
          [0.1168, 0.8148],
          [0.7608, 0.3773],
          [0.5025, 0.5486]],

         [[0.9015, 0.1014],
          [0.5783, 0.9526],
          [0.0922, 0.0233],
          [0.8503, 0.4601]],

         [[0.3661, 0.6779],
          [0.0264, 0.2693],
          [0.2204, 0.4318],
          [0.7275, 0.4968]]]])

Considere tensores como o número de listas que uma dimensão contém. Por exemplo, um tensor (1, 4, 4, 2) terá:

1 lista contendo 4 elementos de 4 elementos de 2 elementos.

A primeira dimensão pode conter 1 elemento.
A segunda dimensão pode conter 4 elementos.
A terceira dimensão pode conter 4 elementos.
A quarta dimensão pode conter 2 elementos.



# Array Numpy x Tensor Pytorch

In [23]:
# array numpy
a = numpy.array(1)

# tensor pytorch
b = torch.tensor(1)

In [26]:
print(a)

1


In [27]:
print(b)

tensor(1)


# Operações com Tensores

In [28]:
t1 = torch.tensor(12)
t2 = torch.tensor(4)
print(t1, t2)

tensor(12) tensor(4)


In [29]:
# adição
print(t1 + t2)

tensor(16)


In [30]:
# subtração
print(t1 - t2)

tensor(8)


In [31]:
# multiplicação
print(t1 * t2)

tensor(48)


In [32]:
# divisao inteira
print(t1 // t2)

tensor(3)


# Operações com Matrizes

In [33]:
# Matriz (tensor rank 2) de numeros randomicos
t_rank2 = torch.randn(3,3)
t_rank2

tensor([[ 0.8112, -1.2626, -1.2074],
        [ 0.2594, -1.1617,  0.7465],
        [ 0.0231,  0.3564,  1.6515]])

In [34]:
# Matriz (tensor rank 3) de numeros randomicos
t_rank3 = torch.randn(3,3,3)
t_rank3

tensor([[[-0.1779, -0.0139, -1.2895],
         [-0.7263,  0.6996, -0.5358],
         [-0.5732, -1.1095, -1.0504]],

        [[-1.0786,  2.3047, -0.3387],
         [-1.1668,  2.4797,  0.8755],
         [-1.2804, -1.5035,  0.0771]],

        [[ 0.6859, -2.1396,  2.3271],
         [ 0.9114, -0.3985, -0.7990],
         [-0.8055, -0.1240, -0.1962]]])

In [35]:
# Matriz (tensor rank 4) de numeros randomicos
t_rank4 = torch.randn(3,3,3,3)
t_rank4

tensor([[[[ 0.7753,  0.6558, -0.7547],
          [-0.8158, -0.1098, -0.0419],
          [ 0.1888,  0.5560, -0.0393]],

         [[-1.3496, -0.5411, -0.5862],
          [ 0.9584,  0.0465,  0.2297],
          [-0.3593,  0.1726,  0.0532]],

         [[-1.4583, -0.0269, -0.4688],
          [ 0.1729,  0.0848,  1.6725],
          [-0.1123,  1.4376,  0.0925]]],


        [[[ 0.8647,  1.1068, -0.2153],
          [-0.2594, -1.8747,  0.2091],
          [ 0.6005, -1.4570, -2.4785]],

         [[-0.4983,  2.1188, -0.6712],
          [ 1.5221, -0.7542, -0.6154],
          [-1.3048,  0.2373, -1.4217]],

         [[ 0.4882,  0.6831, -0.1470],
          [ 0.3909, -0.4671, -1.6125],
          [-2.1376,  2.0037,  0.2779]]],


        [[[ 0.0205,  0.2483,  2.6165],
          [ 0.0349, -1.3809, -0.3062],
          [-1.4140,  0.3276,  0.3564]],

         [[ 1.8971,  0.4382,  0.1966],
          [ 2.0422,  1.0593, -0.8319],
          [ 0.7779,  0.1144,  0.7954]],

         [[ 0.4197,  0.0028, -0.7776],
     

In [36]:
# Multiplicação entre 2 tensores
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = torch.tensor([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [37]:
A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [38]:
B

tensor([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

In [39]:
# mult.
resultado1 = A * B

In [40]:
print(resultado1)

tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])


In [41]:
# matmul
resultado2 = torch.matmul(A, B)

In [42]:
resultado2

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

In [43]:
resultado3 = torch.sum(A * B)

In [44]:
resultado3

tensor(165)

In [45]:
AB1 = A.mm(B)
# ou
AB2 = torch.mm(A, B)
# ou
AB3 = torch.matmul(A, B)
# Ou assim (Python 3.5+)
AB4 = A @ B 

In [46]:
print(AB1)
print(AB2)
print(AB3)
print(AB4)

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])
tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])
tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])
tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])


In [47]:
A @ B

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

In [48]:
# Usando seed para iniciar 2 tensores com valores randômicos
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)


In [49]:
# Adição de matrizes
print(torch.add(a, b))

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]])


In [50]:
# subtração
print(torch.sub(a, b))

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]])


In [51]:
# multiplicação
print(torch.mm(a, b))

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]])


In [52]:
# divisao
print(torch.div(a, b))

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])


In [53]:
# original
print(a, '\n')

# transposta
torch.t(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 



tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])